export const TODO_LIST = {
    GET: "TODO_LIST_GET",
    ADD: "TODO_LIST_ADD",
    COMPLETE: "TODO_LIST_COMPLETE",
    EXPAND: "TODO_LIST_EXPAND",
    DELETE: "TODO_LIST_DELETE",
    FOUND: "TODO_LIST_FOUND",
    FAIL: "TODO_LIST_FAIL",
};